# Site settings
title: CSCI7000-11 Spring 2023
subtitle: Principles of Functional Programming
baseurl: "/csci7000_s23" # the subpath of your site, e.g. /blog/
url: "http://gowthamk.github.io" # the base hostname & protocol for your site
syllabus: ""
githubdir: "gowthamk/csci7000_pfp_s23"

# Author/user information
email: gowtham.kaki@colorado.edu
twitter_username: gowthamk
github_username:  gowthamk
authorurl: "https://gowthamk.github.io"
address: |
    ECCS 121D,
    University of Colorado,
    Boulder, CO 80309

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
